scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']

  - job_name: 'ms-1'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8000']
  
  - job_name: 'ms-2'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8080']